name: Jest run

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  jest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn test
        env:
          AWS_BUCKET_NAME: dummy
          AWS_SECRET_ACCESS_KEY: dummy
          AWS_ACCESS_KEY_ID: dummy
          AWS_REGION: us-east-2
